<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net7.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<UseWPF>true</UseWPF>
	</PropertyGroup>
	<ItemGroup>
		<None Remove="Shaders\shader.frag"/>
		<None Remove="Shaders\shader.vert"/>
		<None Remove="Shaders\tshader.frag"/>
		<None Remove="Shaders\tshader.vert"/>
	</ItemGroup>
	<ItemGroup>
		<Content Include="Shaders\shader.frag">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Shaders\shader.vert">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Shaders\tshader.frag">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Shaders\tshader.vert">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.3.2"/>
		<PackageReference Include="xunit" Version="2.4.2"/>
		<PackageReference Include="xunit.runner.visualstudio" Version="2.4.5">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="coverlet.collector" Version="3.1.2">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Xunit.StaFact" Version="1.1.11"/>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\TypeOTK\TypeOTK.csproj"/>
		<ProjectReference Include="..\TypeDTK\TypeDTK.csproj"/>
	</ItemGroup>
	<ItemGroup>
		<Reference Include="TypeOCore">
			<HintPath>..\TypeOTK\$(OutDir)TypeOCore.dll</HintPath>
		</Reference>
		<Reference Include="TypeD">
			<HintPath>..\TypeOTK\$(OutDir)TypeD.dll</HintPath>
		</Reference>
		<Reference Include="TypeODesktop">
			<HintPath>..\TypeOTK\$(OutDir)TypeODesktop.dll</HintPath>
		</Reference>
	</ItemGroup>
	<ItemGroup Label="TypeOModules">
		<ProjectReference Name="TypeOCore" Include="../../typeocore/TypeOCore/TypeOCore.csproj"/>
		<ProjectReference Name="TypeD" Include="../../typed/TypeD/TypeD.csproj"/>
		<ProjectReference Name="TypeODesktop" Include="../../typeodesktop/TypeODesktop/TypeODesktop.csproj"/>
	</ItemGroup>
	<ItemGroup>
		<Folder Include="Mock\Resources\"/>
	</ItemGroup>
	<ItemGroup>
		<None Update="Mock\Resources\Lato-Black.ttf">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Mock\Resources\texture.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Images\container.jpg">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>